export const unicodeMap = {
    '/': '÷',
    '*': '×',
    'NumLock': '⇭',
    'ArrowUp': '↑',
    'ArrowDown': '↓',
    'ArrowLeft': '←',
    'ArrowRight': '→',
    'Enter': '↵',
    'Backspace': '⌫',
    '!': '!',
    '@': '@',
    '#': '#',
    '%': '%',
    '&': '&',
    '(': '(',
    '_': '_',
    'Alt': '⎇ / ⌥',
    'Meta': '⌘ ⊞',
    'Control': '^',
    'Shift': '⇧',
    'CapsLock': '⇪',
    'Tab': '↹',
    'Escape': '⎋'
}